# Generated by Django 5.0.7 on 2024-08-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donationprofile_cappuccino_donationprofile_cookie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationprofile',
            name='cappuccino',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationprofile',
            name='cookie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationprofile',
            name='gingerbread',
            field=models.IntegerField(default=0),
        ),
    ]
