# Generated by Django 5.0.7 on 2024-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_donationprofile_cappuccino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(max_length=50)),
                ('details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
