# Generated by Django 5.0.7 on 2024-08-11 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='details',
        ),
        migrations.AddField(
            model_name='payment',
            name='donation_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.donationprofile'),
            preserve_default=False,
        ),
    ]
