# Generated by Django 5.0.7 on 2024-08-12 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_payment_author_id_remove_payment_details_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donationprofile',
            table='donation_profiles',
        ),
    ]
