# Generated by Django 5.0.7 on 2024-08-12 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_donationprofile_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='data',
        ),
    ]
