# Generated by Django 5.0.7 on 2024-08-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
