# Generated by Django 5.0.7 on 2024-08-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='donator_email',
            field=models.EmailField(default=11, max_length=254),
            preserve_default=False,
        ),
    ]
