# Generated by Django 5.0.7 on 2024-09-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_buns'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='donator_social_media',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
