# Generated by Django 5.0.7 on 2024-09-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_payment_donator_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='buns',
            name='img_buns',
            field=models.TextField(blank=True, null=True),
        ),
    ]
