# Generated by Django 5.0.7 on 2024-09-10 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_buns_img_buns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationprofile',
            name='cappuccino',
        ),
        migrations.RemoveField(
            model_name='donationprofile',
            name='cookie',
        ),
        migrations.RemoveField(
            model_name='donationprofile',
            name='gingerbread',
        ),
        migrations.CreateModel(
            name='DonationBunQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('bun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.buns')),
                ('donation_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.donationprofile')),
            ],
            options={
                'db_table': 'donation_buns',
                'unique_together': {('donation_profile', 'bun')},
            },
        ),
        migrations.AddField(
            model_name='donationprofile',
            name='buns',
            field=models.ManyToManyField(related_name='donation_profiles', through='accounts.DonationBunQuantity', to='accounts.buns'),
        ),
    ]
