# Generated by Django 5.0.7 on 2024-09-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_donationprofile_cappuccino_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buns',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
