# Generated by Django 5.0.7 on 2024-09-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_buns_created_at_alter_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buns',
            name='created_at',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.CharField(),
        ),
    ]
