# Generated by Django 5.0.7 on 2024-09-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_buns_color_treats'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='donation_message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
