# Generated by Django 5.0.7 on 2024-09-20 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_payment_donation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='donator_email',
            new_name='social_media',
        ),
    ]
