# Generated by Django 5.0.7 on 2024-09-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_donator_email_payment_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationprofile',
            name='status_banned',
            field=models.BooleanField(default=False),
        ),
    ]
