# Generated by Django 5.0.7 on 2024-09-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_donationprofile_status_banned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationprofile',
            name='status_banned',
        ),
    ]
