# Generated by Django 5.0.7 on 2024-10-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_alter_payment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_amount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
