# Generated by Django 5.0.7 on 2024-10-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_payment_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='type_payout',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
